image: node:8

cache:
  paths:
  - node_modules

before_script:
  - yarn install

stages:
  - test
  - build
  - deploy

lint:
  stage: test
  script:
    - yarn run lint

flow:
  stage: test
  script:
    - yarn run flow

unit:
  stage: test
  script:
    - yarn run test

build development:
  stage: build
  script:
    - yarn run build:dev
  artifacts:
    expire_in: 1 month
    paths:
      - build/dev

build beta:
  stage: build
  script:
    - yarn run build:beta
  when: manual
  artifacts:
    expire_in: 1 month
    paths:
      - build/beta

build production:
  stage: build
  script:
    - yarn run build:stable
  when: manual
  artifacts:
    expire_in: 1 month
    paths:
      - build/stable

deploy review:
  stage: deploy
  variables:
    GIT_STRATEGY: none
  dependencies:
    - build development
  script:
    - echo "Deploy a review app"
    - '[ -z "${DEPLOY_BASE_DIR}" ] && echo "Deploy base dir cannot be empty" && exit 255'
    - env
    - mkdir -p "${DEPLOY_BASE_DIR}/${CI_BUILD_REF_NAME}"
    - echo "Copy dev build to web server ${DEPLOY_BASE_DIR}/${CI_BUILD_REF_NAME}..."
    - rsync --delete -va build/dev/ "${DEPLOY_BASE_DIR}/${CI_BUILD_REF_NAME}/"
  only:
    - branches
  tags:
    - deploy
